#!/bin/bash

clear

FARBE_SCHWARZ="\033[30m"
FARBE_ROT="\033[31m"  
FARBE_GRUEN="\033[32m"
FARBE_GELB="\033[33m"
FARBE_BLAU="\033[34m"   
FARBE_MAGENTA="\033[35m"
FARBE_CYAN="\033[36m"   
FARBE_STANDART="\033[37m"

LINIE_GRUEN="${FARBE_GRUEN}|${FARBE_STANDART}"  
KREUZ_GRUEN="${FARBE_GRUEN}+${FARBE_STANDART}" 

LETZTE_LINIE=`tput lines`          
LETZTE_SPALTE=`tput cols`            

CURSOR_X=0   
CURSOR_Y=0   

KEY=()       

if [ ! -n "$1" ] 
then	
	LEVEL=1
else
	if [ $1 -lt 1 ]    
	then
		LEVEL=1
	elif [ $1 -gt 8 ]  
	then
		LEVEL=8
	else
		LEVEL=$1
	fi
fi

sudoku=()	

source ./sudoku_functions/generate.sh ${LEVEL}   

sudoku=(${sudoku_generate[*]})	 

sudoku_buf=(${sudoku[*]})	
	
echo -e "   ************************************************************************"
echo -e "   *  ${FARBE_STANDART}-------------------------------------                               *"              
echo -e "   *  ${FARBE_STANDART}|   |   |   ${LINIE_GRUEN}   |   |   ${LINIE_GRUEN}   |   |   |                               *"              
echo -e "   *  ${FARBE_STANDART}|---+---+---${KREUZ_GRUEN}---+---+---${KREUZ_GRUEN}---+---+---|                               *"              
echo -e "   *  ${FARBE_STANDART}|   |   |   ${LINIE_GRUEN}   |   |   ${LINIE_GRUEN}   |   |   |                               *"             
echo -e "   *  ${FARBE_STANDART}|---+---+---${KREUZ_GRUEN}---+---+---${KREUZ_GRUEN}---+---+---|                               *"            
echo -e "   *  ${FARBE_STANDART}|   |   |   ${LINIE_GRUEN}   |   |   ${LINIE_GRUEN}   |   |   |                               *"             
echo -e "   *  |${FARBE_GRUEN}---+---+---+---+---+---+---+---+---${FARBE_STANDART}|                               *"              
echo -e "   *  ${FARBE_STANDART}|   |   |   ${LINIE_GRUEN}   |   |   ${LINIE_GRUEN}   |   |   |       * * * * * * * * * * * * *"              
echo -e "   *  ${FARBE_STANDART}|---+---+---${KREUZ_GRUEN}---+---+---${KREUZ_GRUEN}---+---+---|       *                       *"              
echo -e "   *  ${FARBE_STANDART}|   |   |   ${LINIE_GRUEN}   |   |   ${LINIE_GRUEN}   |   |   |       * Level:    ${LEVEL}/8         *"              
echo -e "   *  ${FARBE_STANDART}|---+---+---${KREUZ_GRUEN}---+---+---${KREUZ_GRUEN}---+---+---|       *                       *"             
echo -e "   *  ${FARBE_STANDART}|   |   |   ${LINIE_GRUEN}   |   |   ${LINIE_GRUEN}   |   |   |       * * * * * * * * * * * * *"              
echo -e "   *  |${FARBE_GRUEN}---+---+---+---+---+---+---+---+---${FARBE_STANDART}|       *                       *"              
echo -e "   *  ${FARBE_STANDART}|   |   |   ${LINIE_GRUEN}   |   |   ${LINIE_GRUEN}   |   |   |       * Zeit:                 *"            
echo -e "   *  ${FARBE_STANDART}|---+---+---${KREUZ_GRUEN}---+---+---${KREUZ_GRUEN}---+---+---|       *                       *"             
echo -e "   *  ${FARBE_STANDART}|   |   |   ${LINIE_GRUEN}   |   |   ${LINIE_GRUEN}   |   |   |       * * * * * * * * * * * * *"             
echo -e "   *  ${FARBE_STANDART}|---+---+---${KREUZ_GRUEN}---+---+---${KREUZ_GRUEN}---+---+---|       *                       *"            
echo -e "   *  ${FARBE_STANDART}|   |   |   ${LINIE_GRUEN}   |   |   ${LINIE_GRUEN}   |   |   |       *                       *"           
echo -e "   *  ${FARBE_STANDART}-------------------------------------       *                       *"
echo -e "   ************************************************************************"

echo -ne "\033[$((${LETZE_LINIE}));1H" 
echo -ne "\033[0m"
echo -ne "\033[7mDrücke e für Ende oder q für Quit!\033[0m" 


echo -ne "\033[3;9H"        
echo -ne "${FARBE_ROT}"
for i in {0..8}             
do
	for j in {0..8}
	do
		echo -ne "\033[$[ $i * 2 + 3 ];$[ $j * 4 + 9 ]H"  	
		if [ ${sudoku[$[ $i * 9 + $j ]]} -ne 0 ]         
		then
			echo -n "${sudoku[$[ $i * 9 + $j ]]}"
		fi								
	done
done
echo -ne "${FARBE_STANDART}"
echo -ne "\033[3;9H"   


start=$(date "+%s") 



while :                    
do			
	
	read -s -n 1 KEY    
	case ${KEY[0]} in		   
		"A")            
			CURSOR_X=`expr ${CURSOR_X} - 1` 
			if [ ${CURSOR_X} -lt 0 ]
			then
				CURSOR_X=8
				echo -ne "\033[16B" 
			else
				echo -ne "\033[2A" 
			fi
			;;
		"B")	         	
			CURSOR_X=`expr ${CURSOR_X} + 1`  	
			if [ ${CURSOR_X} -gt 8 ]
			then
				CURSOR_X=0
				echo -ne "\033[16A" 
			else
				echo -ne "\033[2B" 
			fi
			;;
		"C")             
			CURSOR_Y=`expr ${CURSOR_Y} + 1`   
			if [ ${CURSOR_Y} -gt 8 ]
			then
				CURSOR_Y=0
				echo -ne "\033[32D"
			else
				echo -ne "\033[4C" 
			fi
			;;
		"D")             
			CURSOR_Y=`expr ${CURSOR_Y} - 1`   
			if [ ${CURSOR_Y} -lt 0 ]
			then
				CURSOR_Y=8
				echo -ne "\033[32C"   
			else
				echo -ne "\033[4D"    
			fi
			;;
		[0-9])           
			if [ ${sudoku[$[ ${CURSOR_X} * 9 + ${CURSOR_Y} ]]} -eq 0 ]   
			then
				sudoku_buf[$[ ${CURSOR_X} * 9 + ${CURSOR_Y} ]]=${KEY[0]} 
				if [ ${KEY[0]} -eq 0 ]
				then
					echo -n " "
				else
					echo -n "${KEY[0]}"
				fi				
				echo -ne "\033[1D"
			fi
			;;
		"e")             		
			source ./sudoku_functions/check.sh ${sudoku_buf[*]}   
			if [[ $return_check -eq 0 ]]  
			then
				tput sc      
				echo -ne "\033[19;54H"        
				echo -ne "                "   	
				echo -ne "\033[19;54H"        
				echo -ne "${FARBE_ROT}SCHAU NOCHMAL DRÜBER${FARBE_STANDART}"
				tput rc      	
			else
				tput sc      
				echo -ne "\033[19;54H"        
				echo -ne "                "   
				echo -ne "\033[19;54H"        
				echo -ne "${FARBE_BLAU}GLÜCKWUNSCH${FARBE_STANDART}"
				tput rc 				
			fi
			;;
		"q")             			    
			echo -ne "\033[${LETZTE_LINIE};1H" 
			echo -ne "\033[K"	 	
			clear
			break
			;;
		*)            
			continue
			;;
	esac
	
	now=$(date "+%s")
	time=$((now-start))
	minute=$((time/60))
	second=$((time-minute*60))

	tput sc  
	
	echo -ne "\033[15;62H"
	echo -ne "        "   	
	echo -ne "\033[15;62H"
	echo -ne "${FARBE_STANDART}${minute} min ${second} sek${FARBE_STANDART}" 
	
	tput rc	
	
done
