#!/bin/bash
#Variabeln
spielfeld=('_' '_' '_' '_' '_' '_' '_' '_' '_')
zeile=0
spalte=0

#Funktionen
function Spielfeld() {
	clear
	echo "${spielfeld[0]} ${spielfeld[1]} ${spielfeld[2]}"
	echo "${spielfeld[3]} ${spielfeld[4]} ${spielfeld[5]}"
	echo "${spielfeld[6]} ${spielfeld[7]} ${spielfeld[8]}"
}

function Abfrage() {
	if  [ "${spielfeld[0]}" == "${spielfeld[1]}" ] && [ "${spielfeld[1]}" == "${spielfeld[2]}"    ] && [ "${spielfeld[1]}" != '_'  ]
	then
		b=0
	elif [ "${spielfeld[3]}" == "${spielfeld[4]}"    ] && [ "${spielfeld[4]}" == "${spielfeld[5]}"    ] && [ "${spielfeld[4]}" != '_'   ]
	then
		b=0
	elif [ "${spielfeld[6]}" == "${spielfeld[7]}"    ] && [ "${spielfeld[7]}" == "${spielfeld[8]}"    ] && [ "${spielfeld[7]}" != '_'   ]
	then
		b=0
	elif [ "${spielfeld[0]}" == "${spielfeld[3]}"    ] && [ "${spielfeld[3]}" == "${spielfeld[6]}"    ] && [ "${spielfeld[3]}" != '_'   ]
	then
		b=0
	elif [ "${spielfeld[1]}" == "${spielfeld[4]}"    ] && [ "${spielfeld[4]}" == "${spielfeld[7]}"    ] && [ "${spielfeld[4]}" != '_'   ]
	then
		b=0
	elif [ "${spielfeld[2]}" == "${spielfeld[5]}"    ] && [ "${spielfeld[5]}" == "${spielfeld[8]}"    ] && [ "${spielfeld[5]}" != '_'   ]
	then
		b=0
	elif [ "${spielfeld[0]}" == "${spielfeld[4]}"    ] && [ "${spielfeld[4]}" == "${spielfeld[8]}"    ] && [ "${spielfeld[4]}" != '_'   ]
	then
		b=0
	elif [ "${spielfeld[2]}" == "${spielfeld[4]}"    ] && [ "${spielfeld[4]}" == "${spielfeld[6]}"    ] && [ "${spielfeld[4]}" != '_'   ]
	then
		b=0
	else
		b=1
	fi
}

function Abfragespieler(){
	clear
	Spielfeld
	echo "Spieler $1 [$2]"
	while true; do
		echo Spalte 1, 2  oder 3?
		read spalte

		if [ "$spalte" -ge 4 ] || [ "$spalte" -le 0 ]; then
			echo Bitte wiederholen
			continue
		else
			break
		fi
	done

	while true; do
		echo Zeile 1,  2  oder 3 ?
		read zeile

		if [ "$zeile" -ge 4 ] || [ "$zeile" -le 0 ];then
			echo Bitte wiederholen
			continue
		else
			break
		fi
	done

	idx=$(( ($zeile-1)*3 + ($spalte-1) ))
	if [ "${spielfeld[idx]}" == '_' ]; then
		return
	else
		echo "Position Belegt"
		sleep 1
		Abfragespieler "$1" "$2"
	fi
}

function Sieg() {
	if [ $b == 0 ];then
		echo Spieler "$1" hat gewonnen!
		exit 0
	fi
}

function Setzen () {
	idx=$(( ($zeile-1)*3 + ($spalte-1) ))
	if [ "${spielfeld[idx]}" == '_' ]; then
		spielfeld[$idx]=$1
	fi
	
}

function Spielerzug() {
		Spielfeld
		Abfragespieler "$1" "$2"
		Setzen "$2"
		Spielfeld
		Abfrage
		Sieg "$1"
}

function main() {
	while true; do
		Spielerzug 1 X
		Spielerzug 2 O
	done
}
#- - - - - - - -

main