#!/usr/bin/env bash
#!/usr/bin/env bash
#Check if user root
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

apt install git-all -y
clear
git clone https://github.com/LegendRed01/Bash_Scripting.git /bin 
clear
echo Koop IT 10 Games Launcher installiert