#!/usr/bin/env bash
#Check if user root
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

echo "Installiere Abhängikeiten"
apt install git -y &> /dev/null
echo "Lade installations dateine Runter"
rm -r /tmp/koopit &> /dev/null
git clone https://github.com/LegendRed01/Bash_Scripting.git /tmp/koopit &> /dev/null
rm /tmp/koopit/README.md &> /dev/null;rm /tmp/koopit/installer &> /dev/null;
rm /bin/it10games &> /dev/null
rm -r /bin/games &> /dev/null
 

chmod a+x /tmp/koopit/it10games &> /dev/null
chmod a+x /tmp/koopit/games/* &> /dev/null
mv /tmp/koopit/* /usr/bin

#clear
echo Koop IT 10 Games Launcher installiert
