#!/usr/bin/env bash
#Check if user root
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

apt install git -y
clear
git clone https://github.com/LegendRed01/Bash_Scripting.git /bin/koopit
path=$(cat /etc/environment)
if [[ $path =~ "koopit" ]]; then
    echo "Added"
else
    path=$(cat /etc/environment)
    path_edit=${path::-1}:/bin/koopit\"
    echo "$path_edit" > /etc/environment
fi
export PATH=$PATH:/bin/koopit

chmod a+x /bin/koopit/it10games
chmod a+x /bin/koopit/games/*
#clear
echo Koop IT 10 Games Launcher installiert