#!/usr/bin/env bash
declare -a avalible_games=( $(ls games) )
declare -i current_game=0
clear

function DisplayTitle () {
    local title=$(tput setaf 105) 
    local color=$(tput setaf 127)
    local normal=$(tput sgr0)
    printf "$title"
    printf "_  _ ____ ____ ___     _ ___    ____ ___  _ ____ _    ____ ____ ____ _  _ _  _ _    _  _ _  _ ____\n" 
    printf "|_/  |  | |  | |__] __ |  |     [__  |__] | |___ |    |___ [__  |__| |\/| |\/| |    |  | |\ | | __\n" 
    printf "| \_ |__| |__| |       |  |     ___] |    | |___ |___ |___ ___] |  | |  | |  | |___ |__| | \| |__]\n"                                                                                                
    printf "$color"
    printf "                 ____ _  _ ____ _  _ ____    ___  _ ____    ____ _ _  _ \n"                             
    printf "                 [__  |  | |    |__| |___    |  \ | |__/    |___ | |\ |\n"                              
    printf "                 ___] |__| |___ |  | |___    |__/ | |  \    |___ | | \|\n"                              
    printf "                                                                       \n"                              
    printf "                       ____ ___  _ ____ _       ____ _  _ ____         \n"                              
    printf "                       [__  |__] | |___ |       |__| |  | [__          \n"                              
    printf "                       ___] |    | |___ |___    |  | |__| ___]         \n"   
    printf "$normal"       
}

function SetCursor () {
    tput cup $1 $2
}

function GameSelector () {
    local green=$(tput setaf 123) 
    local normal=$(tput sgr0)
    for((g=0;g<${#avalible_games[@]};g++)); do
        game=${avalible_games[g]}
        tput cup $(( 11 + $g )) 40
        if [ $current_game -eq $g ]; then
            echo "${green}[${game}]${normal}           "
        else
            echo " ${game}              "
        fi
    done   
}

function PrintSelector () {
    SetCursor 0 0
    DisplayTitle
    GameSelector
}

function SelectorUp () { 
    if [ $current_game -gt 0 ]; then
         current_game=$(( $current_game -1 ))
    fi  
}

function SelectorDown () {
      if [ $current_game -lt $(( ${#avalible_games[@]} - 1)) ]; then
         current_game=$(( $current_game + 1 ))
    fi  
}
function StartGame () {
    ./games/${avalible_games[$current_game]}
    clear
    PrintSelector
}

function getKeyStroke () {
    read -r -sn1 t
    case $t in
        q) exit 1 ;;
        '') StartGame;;
        ($'\033') 
        read -t.001 -n2 r
        case "$r" in
            ('[A') SelectorUp;;
            ('[B') SelectorDown;;
        esac
    esac
}


while true; do
    PrintSelector
    getKeyStroke
done
